source 'https://rubygems.org'
ruby '3.0.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 7.0'
gem 'devise', '~> 4.8', '>= 4.8.1'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.2', '>= 1.2.3'
# Use Puma as the app server
gem 'puma', '~> 5.5', '>= 5.5.2'
# Use SCSS for stylesheets
gem 'bootstrap-sass', '~> 3.4', '>= 3.4.1'
gem 'bootstrap_form', '~> 5.0'
gem 'sass-rails', '~> 6.0'
gem 'jquery-rails', '~> 4.4'
gem 'will_paginate', '~> 3.3', '>= 3.3.1'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '~> 4.2'
gem 'faker', '~> 2.19'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 5.0'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5.2', '>= 5.2.1'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.11', '>= 2.11.5'
gem 'gon', '~> 6.4'
gem 'actionpack', '~> 7.0'
gem 'activesupport', '~> 7.0'
gem 'railties', '~> 7.0'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', '~> 11.1', '>= 11.1.3', platforms: [:mri, :mingw, :x64_mingw]
  # Adds support for Capybara system testing and selenium driver
  gem 'rspec-rails', '~> 5.0', '>= 5.0.2'
  gem 'factory_girl_rails', '~> 4.9'
  gem 'rails-controller-testing', '~> 1.0', '>= 1.0.5'
  gem 'headless', '~> 2.3', '>= 2.3.1'
  gem 'capybara', '~> 3.36'
  gem 'poltergeist', '~> 1.18', '>= 1.18.1'
  gem 'database_cleaner', '~> 2.0', '>= 2.0.1'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '~> 4.2'
  gem 'listen', '~> 3.7'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring', '~> 2.1.1'
  gem 'spring-watcher-listen', '~> 2.0', '>= 2.0.1'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', '~> 1.2021', '>= 1.2021.5', platforms: [:mingw, :mswin, :x64_mingw, :jruby]